### ISSUE TITLE
Ansible: Add playbook specifically for adding ssh keys

### ISSUE THREAD

**Issue by ssoriche** [metacpan/metacpan-ansible#36]
The HZ cluster uses an immutable OS as the host for k8s, as such there is only 1 user account (core), and any users that should require local access (this should be very limited) should have their ssh public keys added to this user via Ansible. 

No other Ansible management should occur with this cluster.

**Comment by ranguard** [comment]
Now trying to skip Ansible and go straight for K8s - closing
